ui: mocha-bdd
browsers:
  - name: chrome
    version: ["45", "latest"]
  - name: ie
    version: ["9", "10", "latest"]
  - name: firefox
    version: ["36", "latest"]
  - name: android
    version: ["5.0", "5.1", "6.0"]
  - name: safari
    version: ["7", "latest"]
